# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 3050:80

  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
    expose:
      - 3001
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - ./api:/app

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    expose:
      - 3000
    volumes:
      - /app/node_modules
      - ./client:/app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
  